name: Build & deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.Js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Build lib
        run: npm run build
      - name: Deploy lib to npmjs.org
        run: npm publish --access public
        env:
          NODE_AUTH_MODEL: ${{ secrets.NPM_TOKEN }}
