name: Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.Js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Run ESLint
        run: npm run lint
